<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Menu_PageLogo-image</name>
   <tag></tag>
   <elementGuidId>38597528-b137-4b6e-b21d-1aa75d96c3c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.PageLogo-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://amazon-blogs-brightspot-lower.s3.amazonaws.com/about/00/92/0260aab44ee8a2faeafde18ee1da/amazon-logo-inverse.svg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6dd02970-02bb-4dad-85e6-7ebde91a8e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PageLogo-image</value>
      <webElementGuid>cf964134-ca9a-41f0-9211-59a978f617df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://amazon-blogs-brightspot-lower.s3.amazonaws.com/about/00/92/0260aab44ee8a2faeafde18ee1da/amazon-logo-inverse.svg</value>
      <webElementGuid>6df3ac4e-20c0-4f22-a638-d649cf1dd954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>117</value>
      <webElementGuid>f7a4e9af-9820-4160-a9c5-e879bd1879c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;Homepage&quot;]/body[@class=&quot;Homepage-body&quot;]/header[@class=&quot;Homepage-header&quot;]/div[@class=&quot;Homepage-header-bottom&quot;]/ps-header[@class=&quot;Page-header&quot;]/div[@class=&quot;Page-header-wrapper&quot;]/div[@class=&quot;Page-header-bar&quot;]/div[@class=&quot;Page-header-bar-logo&quot;]/span[1]/a[1]/img[@class=&quot;PageLogo-image&quot;]</value>
      <webElementGuid>ffe5ebee-eb65-4e0c-87a6-b24d63cfa616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://amazon-blogs-brightspot-lower.s3.amazonaws.com/about/00/92/0260aab44ee8a2faeafde18ee1da/amazon-logo-inverse.svg')]</value>
      <webElementGuid>020dcd9b-9a69-4277-ae18-0f4f92c9af6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>828f594a-8f92-4b1b-a00f-bc01bf23e926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://amazon-blogs-brightspot-lower.s3.amazonaws.com/about/00/92/0260aab44ee8a2faeafde18ee1da/amazon-logo-inverse.svg']</value>
      <webElementGuid>43f86437-b6ae-4098-92df-8d1792da336f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
