<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_se_PageLogo-image</name>
   <tag></tag>
   <elementGuidId>e0e9e90b-d086-4f7c-9463-7abf771e167d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Page-footer-logo > a > img.PageLogo-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://amazon-blogs-brightspot-lower.s3.amazonaws.com/about/a9/af/27a4ef844ac38129d0fa460675fb/amazon-logo.svg')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e37b0779-46f2-4b1d-8742-6fe5f5bf37d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PageLogo-image</value>
      <webElementGuid>28ce0cd1-aa67-426f-ace8-6d29bffc8333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://amazon-blogs-brightspot-lower.s3.amazonaws.com/about/a9/af/27a4ef844ac38129d0fa460675fb/amazon-logo.svg</value>
      <webElementGuid>67c54be0-b95a-457f-9484-024c7d4671cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>117</value>
      <webElementGuid>7be7902a-b856-4b17-a447-0c010a837b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;Homepage&quot;]/body[@class=&quot;Homepage-body&quot;]/footer[@class=&quot;Page-footer&quot;]/div[@class=&quot;Page-footer-body&quot;]/div[@class=&quot;Page-footer-body-main&quot;]/div[@class=&quot;Page-footer-columns&quot;]/div[@class=&quot;Page-footer-column&quot;]/div[@class=&quot;Page-footer-logo&quot;]/a[1]/img[@class=&quot;PageLogo-image&quot;]</value>
      <webElementGuid>4294da25-b4fb-48bb-a6a9-4a9410773eba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://amazon-blogs-brightspot-lower.s3.amazonaws.com/about/a9/af/27a4ef844ac38129d0fa460675fb/amazon-logo.svg')])[2]</value>
      <webElementGuid>ef21b2d0-e124-45b8-9403-010c0b163dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>aab56d32-8b1c-49ec-8968-dcf5042633cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://amazon-blogs-brightspot-lower.s3.amazonaws.com/about/a9/af/27a4ef844ac38129d0fa460675fb/amazon-logo.svg']</value>
      <webElementGuid>39f80e83-21c3-45af-9357-68d00f7edcf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
